# -*- coding: utf-8 -*-
"""Programme complet 3AS LG Algérie (BAC Langues Étrangères).
Matières: Allemand, Anglais, Français, Arabe, Espagnol, Italien,
Histoire, Géographie, Philosophie, Sciences Islamiques, Maths.
Chaque entrée: (matiere, chapitre, contenu, explication, ordre)
Explications simplifiées niveau débutant, FR/AR selon matière.
"""
COURSES = [
# ================= ALLEMAND (20) =================
("Allemand","01. Präsens - Verbes réguliers & irréguliers",
"Conjugaison présent: ich lerne, du lernst, er lernt... Verbes irréguliers: sprechen→spricht, lesen→liest, fahren→fährt, sein/haben. Ex: Ich spreche Deutsch.",
"Retiens: 2e/3e personne changent souvent e→i/ie, a→ä. Apprends sein/haben par cœur, ils servent partout.",1),
("Allemand","02. Perfekt (Passé composé)",
"haben/sein + Partizip II. Ex: Ich habe gelernt / Ich bin gegangen. Participe: ge- + radical + -t (faibles) / -en (forts).",
"Choisis l'auxiliaire: mouvement/changement d'état → sein, sinon haben. Astuce BAC: repère habe/hast... + ge-...-t.",2),
("Allemand","03. Präteritum (Imparfait / passé narratif)",
"Formes: lernte, sprach, ging, war, hatte. Utilisé dans récits écrits BAC. Ex: Er ging zur Schule.",
"À l'écrit BAC, préfère Präteritum pour raconter. Retiens war/hatte/ging/kam.",3),
("Allemand","04. Futur & Plusquamperfekt",
"Futur: werden + Infinitiv (Ich werde lernen). Plusquamperfekt: hatte/war + Partizip II (Nachdem ich gelernt hatte...).",
"werden + infinitif = futur. hatte/war + participe = plus-que-parfait après nachdem.",4),
("Allemand","05. Modalverben (können, müssen, wollen, sollen, dürfen, mögen)",
"können (pouvoir), müssen (devoir), wollen (vouloir), sollen (devoir moral), dürfen (avoir le droit), möchten (aimerais). Verbe principal à l'infinitif en fin. Ex: Ich muss lernen.",
"2e verbe toujours à la fin à l'infinitif. möchten = politesse, très utilisé au BAC.",5),
("Allemand","06. Trennbare & untrennbare Verben",
"Séparables: anrufen→ruft...an, aufstehen, mitbringen. Inséparables: bekommen, verstehen, erzählen. Ex: Ich rufe dich an.",
"Si préfixe accentué (an-, auf-, mit-) → se sépare. be-, ver-, er- → ne se sépare jamais.",6),
("Allemand","07. Deklination: Nominativ, Akkusativ, Dativ",
"der→den→dem, die→die→der, das→das→dem, die(pl)→die→den. Prépositions AKK: für, ohne, gegen. DAT: mit, nach, bei, von, zu.",
"Apprends par groupes de prépositions. Question BAC classique: mit + Dativ.",7),
("Allemand","08. Passiv (Voix passive)",
"werden + Partizip II: wird gebaut, wurde gebaut, ist gebaut worden. Ex: Das Haus wird gebaut.",
"Repère wird/wurde/worden = passif. En français 'être + participe'. Sujet BAC fréquent.",8),
("Allemand","09. Konjunktiv II (souhait, politesse, irréel)",
"wäre, hätte, würde + Infinitiv. Wenn ich Zeit hätte, würde ich reisen. Ex politesse: Ich hätte gern...",
"3 mots magiques: wäre/ hätte/ würde. Si + imparfait imaginaire = rêve.",9),
("Allemand","10. Relativsätze",
"der/die/das/den/dem/dessen/deren. Verbe à la fin. Ex: Der Mann, der dort steht, ist Lehrer.",
"Comme qui/que mais accordé. Verbe toujours dernier mot de la relative.",10),
("Allemand","11. Kausalsätze (weil, da, denn)",
"weil + verbe fin: Ich lerne, weil ich Erfolg haben will. denn + ordre normal. Ex BAC: Umwelt schützen, weil...",
"weil envoie le verbe à la fin, denn ne change rien. Ne les mélange pas.",11),
("Allemand","12. Finalsätze & Konsekutiv (damit, um...zu, sodass)",
"damit + sujet différent, um...zu + même sujet. Ex: Ich lerne, um zu bestehen. sodass = conséquence.",
"même sujet → um...zu, sujets différents → damit.",12),
("Allemand","13. Konzessiv & Konditional (obwohl, wenn, falls)",
"obwohl + verbe fin (bien que). wenn/falls = si. Ex: Obwohl es schwer ist, lerne ich.",
"obwohl = concession BAC (avantages/inconvénients). Verbe à la fin.",13),
("Allemand","14. Komparativ & Superlativ",
"klein→kleiner→am kleinsten, gut→besser→am besten. als (différence), wie (égalité). Ex: Deutsch ist leichter als Mathe.",
"Retiens irréguliers: gut/besser, viel/mehr, gern/lieber.",14),
("Allemand","15. Infinitiv mit zu & Infinitivsätze",
"Es ist wichtig, Deutsch zu lernen. ohne...zu, anstatt...zu. Ex BAC opinion.",
"zu + infinitif après adjectifs/expressions. Virgule avant.",15),
("Allemand","16. Wortschatz: Umwelt, Technologie, Gesundheit",
"die Umwelt, der Klimawandel, nachhaltig, die Energie, das Handy, die Medien, gesund/krank, der Sport. 5 mots/jour avec phrase.",
"Crée tes cartes: mot + article + 1 phrase. Les articles rapportent des points.",16),
("Allemand","17. Wortschatz: Jugend, Bildung, Gesellschaft",
"die Jugend, die Ausbildung, der Beruf, die Gesellschaft, die Familie, die Freundschaft. Thèmes BAC 2020-2025.",
"Thèmes BAC récurrents: Jugendprobleme, Studium, Soziale Netzwerke.",17),
("Allemand","18. Leseverstehen - Méthode BAC",
"1) Lire questions avant texte 2) Surligner mots-clés 3) Richtig/Falsch + justifier avec citation 4) Titre = idée générale.",
"Ne traduis pas tout: cherche les réponses aux questions d'abord. Gagne 20 min.",18),
("Allemand","19. Textproduktion: Meinung äußern (expression BAC)",
"Plan: Einleitung (Thema), Hauptteil (Vorteile/Nachteile + Beispiele), Schluss (eigene Meinung). Connecteurs: zunächst, außerdem, jedoch, meiner Meinung nach, abschließend.",
"Apprends 15 connecteurs + 3 plans types. 120-150 mots, paragraphes.",19),
("Allemand","20. BAC Blancs & Sujets types",
"Sujets: Soziale Netzwerke, Umweltschutz, Jugend und Zukunft. Structure épreuve: Teil 1 Leseverstehen (7pts), Teil 2 Sprachfähigkeit (8pts), Teil 3 Schreiben (5pts).",
"Entraîne-toi en temps réel 2h. Relis les corrigés 2008-2025.",20),
# ================= ANGLAIS (10) =================
("Anglais","01. All Tenses - Révision BAC",
"Present simple/continuous, Past simple/continuous, Present perfect, Past perfect, Future. Ex: I have lived here since 2020.",
"Timeline: past→perfect, now→simple/continuous, result→perfect. Since + date, for + durée.",21),
("Anglais","02. Reported Speech",
"She said 'I am tired' → She said she was tired. Backshift: present→past, will→would, can→could.",
"Recule d'un temps. Pronoms et lieux changent aussi: here→there.",22),
("Anglais","03. Conditionals 0-3 + Wish",
"Type1: If+present, will. Type2: If+past, would. Type3: If+past perfect, would have +PP. I wish I were...",
"0 vérité, 1 réel, 2 rêve, 3 regret. Wish + past = regret présent.",23),
("Anglais","04. Passive Voice",
"be + PP: is built, was built, has been built. Ex: English is spoken here.",
"Repère be + participe. Agent avec by souvent omis.",24),
("Anglais","05. Relative Clauses & Modals",
"who/which/that/whose. Modals: can, must, should, might. Ex: You should revise.",
"Should = conseil BAC. Whose = dont (possession).",25),
("Anglais","06. Expressing Opinion & Agreement",
"I believe, In my view, Admittedly... However... BAC essay: introduction, 3 arguments, conclusion.",
"3 connecteurs d'opposition + 3 d'addition minimum par essai.",26),
("Anglais","07. Theme: Ethics - Corruption, Fraud",
"Vocab: bribery, embezzlement, transparency. Textes BAC filière langues: fight against corruption.",
"Apprends 10 mots + 2 exemples Algérie/monde par thème.",27),
("Anglais","08. Theme: Education & Civilization",
"Vocab: literacy, curriculum, ancient civilizations, cultural heritage. Ex: Education builds nations.",
"Thème BAC récurrent: rôle de l'éducation dans le progrès.",28),
("Anglais","09. Reading Comprehension Method",
"Skim (idée), Scan (détails), True/False + justification, Reference words (it, they = ?).",
"Justifie toujours avec la phrase du texte entre guillemets.",29),
("Anglais","10. BAC Writing: Expository Essay",
"Plan 4 paragraphes: intro (thesis), 2-3 body (topic sentence + support), conclusion (restate). 150-200 mots.",
"1 idée = 1 paragraphe. Relis verbes/temps.",30),
# ================= FRANÇAIS (8) =================
("Français","01. Le texte argumentatif (cœur du BAC)",
"Thèse, arguments, exemples, connecteurs. Plans: pour/contre, concessif, analytique. Repérer thèse dès l'intro.",
"Question BAC: 'Quelle est la thèse ?' = 1re phrase d'opinion. 3 arguments = 3 paragraphes.",31),
("Français","02. Figures de style BAC",
"Métaphore, comparaison, anaphore, hyperbole, antithèse, personnification. 1 définition + 1 exemple chacune.",
"Comparaison = avec outil (comme), métaphore = sans outil.",32),
("Français","03. Discours rapporté & voix",
"Direct→indirect: temps reculés, pronoms changés. Active→passive: être + participe.",
"Guillemets disparaissent à l'indirect. Accord du participe avec être.",33),
("Français","04. Le compte-rendu objectif/subjectif",
"Objectif: résumer sans avis (il, présent). Subjectif: + critique (je, adjectifs). Structure BAC langues.",
"120 mots objectif. Ne donne jamais ton avis dans l'objectif.",34),
("Français","05. Essai & synthèse BAC",
"Problématique, 3 parties, exemples littéraires/actuels. Phrases de transition.",
"Intro: amorce + problématique + plan. Conclusion: réponse + ouverture.",35),
("Français","06. Histoire littéraire: siècles & mouvements",
"Romantisme, Réalisme, Symbolisme, Existentialisme. Auteurs: Hugo, Baudelaire, Camus (Algérie).",
"Camus = atout copie en Algérie. 1 citation par mouvement.",36),
("Français","07. Grammaire BAC: subordonnées",
"Relative, complétive, circonstancielle (cause, conséquence, but, concession). Connecteurs.",
"Repère le mot subordonnant → nature → fonction.",37),
("Français","08. Méthode épreuve BAC",
"Compréhension (13pts): QCM, vrai/faux justifié, titre, résumé. Production (7pts): essai/compte-rendu.",
"Gère 2h: 1h15 compréhension, 45 min production.",38),
# ================= ARABE (8) =================
("Arabe","01. البناء الفكري - تحليل النص",
"الفكرة العامة، الأفكار الأساسية، العاطفة، النمط (وصفي/حجاجي). أسئلة BAC أدبية ثابتة.",
"احفظ منهجية الإجابة: الفكرة = جملة اسمية مختصرة.",39),
("Arabe","02. البناء اللغوي - الإعراب",
"النواسخ (كان/إن)، الممنوع من الصرف، البدل والعطف، إعراب الجمل. تدريب BAC لغات.",
"ركز على إعراب المفردات + الجمل التي لها محل.",40),
("Arabe","03. البلاغة: التشبيه والاستعارة",
"التشبيه (مشبه/مشبه به/أداة)، الاستعارة (تصريحية/مكنية). أمثلة BAC.",
"إذا ذُكر المشبه به → تصريحية، إذا حُذف → مكنية.",41),
("Arabe","04. البلاغة: الكناية والمحسنات",
"الكناية، الطباق، المقابلة، السجع، الجناس. أثرها البلاغي.",
"احفظ الأثر: التوكيد، التجميل، الإيقاع.",42),
("Arabe","05. العروض: البحور BAC",
"الطويل، البسيط، الكامل، الوافر. الكتابة العروضية والرموز.",
"تدرب على التقطيع: متحرك / ساكن.",43),
("Arabe","06. الشعر: المهجر والالتزام",
"شعراء المهجر (جبران)، الشعر الحر، القضية الفلسطينية والثورة الجزائرية.",
"اربط الشاعر بالقضية: الالتزام = موقف.",44),
("Arabe","07. النثر: المقال والمسرح",
"المقال (مقدمة/عرض/خاتمة)، المسرحية، القصة. خصائص كل فن.",
"المقال BAC: ذاتي/موضوعي، منهج الاستقراء.",45),
("Arabe","08. منهجية BAC عربية",
"البناء الفكري 10ن + اللغوي 06ن + التقويم النقدي 04ن. إدارة 2h30.",
"التقويم النقدي = رأي + تعليل + شواهد.",46),
# ================= ESPAGNOL (6) =================
("Espagnol","01. Presente & Pretéritos",
"Presente: hablo, comes. Pretérito perfecto: he hablado. Indefinido: hablé. Imperfecto: hablaba.",
"Indefinido = action finie datée, Imperfecto = habitude/description.",47),
("Espagnol","02. Futuro & Condicional",
"hablaré, hablaría. Ex: Me gustaría estudiar. Cortesía BAC.",
"Condicional = souhait/politesse comme français.",48),
("Espagnol","03. Subjuntivo presente",
"hable, coma, viva. Après: quiero que, es necesario que, ojalá.",
"Subjonctif après volonté/émotion/nécessité.",49),
("Espagnol","04. Imperativo & Ser/Estar",
"habla/hable. Ser = identité, Estar = état/lieu. Ex: Estoy cansado.",
"Ser + adjectif permanent, Estar + temporaire.",50),
("Espagnol","05. Opinión BAC",
"Creo que, En mi opinión, Sin embargo, Por lo tanto. Redacción 120 palabras.",
"3 párrafos + conectores = nota alta.",51),
("Espagnol","06. Comprensión BAC",
"Verdadero/Falso + justificación, título, léxico. Temas: juventud, medio ambiente.",
"Justifica siempre con frase del texto.",52),
# ================= ITALIEN (3) =================
("Italien","01. Base: presente & passato prossimo",
"parlo, ho parlato, sono andato. Articoli: il/lo/la/i/gli/le.",
"Essere pour mouvement, avere sinon.",53),
("Italien","02. Futuro & condizionale",
"parlerò, vorrei. Cortesia BAC.",
"Vorrei = j'aimerais, clé de l'expression.",54),
("Italien","03. Opinione BAC",
"Penso che + congiuntivo, Secondo me. Temi: giovani, ambiente.",
"Congiuntivo après penso che.",55),
# ================= HISTOIRE (5) =================
("Histoire","01. Le monde en 1945 & Guerre froide",
"Yalta/Potsdam, bipolarisation USA/URSS, Truman/Jdanov, OTAN/Pacte Varsovie, crises: Corée, Cuba, Vietnam.",
"Frise 1945-1991. 2 blocs + 2 doctrines = intro parfaite.",56),
("Histoire","02. Coexistence pacifique & Détente",
"Khrouchtchev, coexistence, SALT, Helsinki 1975. Puis 2e guerre froide (Afghanistan).",
"Dates: 1953 mort Staline, 1962 Cuba, 1975 Helsinki.",57),
("Histoire","03. Décolonisation & Tiers-monde",
"Inde 1947, Algérie 1962, Non-alignés Bandung 1955. Causes/étapes.",
"Bandung = naissance Tiers-monde. Citer 2 exemples.",58),
("Histoire","04. L'Algérie 1945-1962",
"Massacres 8 mai 1945, PPA/MTLD, 1er nov 1954, Congrès Soummam 1956, Évian 1962.",
"5 dates = 5 paragraphes. Soummam = organisation.",59),
("Histoire","05. L'Algérie depuis 1962 & monde actuel",
"Indépendance, 1965, 1988, monde unipolaire, 11 sept 2001, mondialisation.",
"Relie national/international dans la conclusion.",60),
# ================= GÉOGRAPHIE (4) =================
("Géographie","01. Mondialisation & échanges",
"Flux, FTN, Nord/Sud, BRICS. Schémas BAC.",
"Croquis: centres/périphéries.",61),
("Géographie","02. Les USA, 1re puissance",
"Atouts, rayonnement, limites. Étude de cas BAC.",
"Plan: atouts/manifestations/limites.",62),
("Géographie","03. L'UE & l'Asie",
"UE intégration, Chine/Japon. Comparer.",
"Cartes: mégalopoles, façades.",63),
("Géographie","04. L'Algérie: territoire & économie",
"Hydrocarbures, agriculture, aménagement, défis. Chiffres clés.",
"Apprends 5 chiffres récents.",64),
# ================= PHILOSOPHIE LG (5) =================
("Philosophie","01. Méthode dissertation & texte BAC",
"Problématiser, plan dialectique (thèse/antithèse/synthèse), texte: dégager thèse + argument.",
"Intro: amorce + problème + plan. 4h: 1h brouillon.",65),
("Philosophie","02. Conscience & inconscient",
"Descartes (cogito), Freud (ça/moi/surmoi), Sartre (mauvaise foi). Suis-je transparent à moi-même ?",
"1 auteur par position + 1 exemple.",66),
("Philosophie","03. Autrui, État & justice",
"Sartre (enfer), Lévinas (visage), Hobbes/Rousseau (contrat), justice/égalité.",
"Sujet BAC LG fréquent: autrui m'aliène-t-il ?",67),
("Philosophie","04. Travail, morale & bonheur",
"Marx (aliénation), Kant (devoir), Épicure/Stoïciens (bonheur). Le travail libère-t-il ?",
"Cite impératif catégorique Kant.",68),
("Philosophie","05. Vérité & raison",
"Doute cartésien, science/pop­per (réfutation), vérité/correspondance. Peut-on tout démontrer ?",
"Distingue croire/savoir.",69),
# ================= SCIENCES ISLAMIQUES (6) =================
("Sciences Islamiques","01. العقيدة: الإيمان وأركانه",
"أركان الإيمان الستة، التوحيد، الشرك. آيات وأحاديث.",
"احفظ دليلاً نقلياً لكل ركن.",70),
("Sciences Islamiques","02. العبادات: الصلاة والزكاة والصوم",
"الأحكام، الشروط، المقاصد. BAC: الحكمة من التشريع.",
"اربط الحكم بالمقصد (تزكية النفس).",71),
("Sciences Islamiques","03. المعاملات: البيع والربا",
"أركان البيع، الربا أنواعه وحكمه. آيات البقرة.",
"قاعدة: كل قرض جر نفعاً فهو ربا.",72),
("Sciences Islamiques","04. الأسرة والميراث",
"الزواج، الطلاق، الميراث وأنصبته. مسائل تطبيقية.",
"تدرب على مسائل: 1/2، 1/4، 1/8، 2/3.",73),
("Sciences Islamiques","05. مقاصد الشريعة",
"الضروريات الخمس: الدين، النفس، العقل، النسل، المال. الترتيب.",
"مثال لكل مقصد من الواقع.",74),
("Sciences Islamiques","06. منهجية BAC",
"حفظ الآيات (التوبة/البقرة المقررة)، شرح المفردات، الاستشهاد.",
"اكتب الآية صحيحة + رقم السورة.",75),
# ================= MATHS LG (3) =================
("Maths","01. Suites (niveau littéraire)",
"arithmétique/géométrique, terme général, somme. Ex BAC simples.",
"Formules: Un=U0+n·r, Un=U0·q^n.",76),
("Maths","02. Fonctions & dérivation",
"dérivée, tableau variations, limites simples. Courbes.",
"f'=0 → extremum. Signe → sens.",77),
("Maths","03. Probabilités & stats",
"arbres, p(A∪B), moyenne/médiane. Ex concrets BAC.",
"Dénombrement simple, pas de combinatoire lourde.",78),
]
